spring:
  application:
    name: notesWeb

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
      file-size-threshold: 2KB #Large files will be temporarily saved to the hard drive instead of being kept in RAM

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/NoteApp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
      naming:
        # Automatically convert CamelCase (Java) to under_score (PostgreSQL)
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:note-update-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

    stomp:
      relay-host: ${RABBIT_HOST:localhost}
      relay-port: ${RABBIT_STOMP_PORT:61613}
      login: ${RABBIT_USERNAME:guest}
      passcode: ${RABBIT_PASSWORD:guest}

  jackson:
    serialization:
      # Avoid date formatting errors when sending data Kafka/Swagger.
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8081}

  #expired time for timeout server
  tomcat:
    threads:
      max: 1000
      min-spare: 100
    connection-timeout: 60000

jwt:
  secret: ${JWT_SECRET:your_default_secret_for_dev_only}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh: ${JWT_REFRESH:604800000}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ${LOG_SQL_LEVEL:INFO}
    org.springframework.kafka: ERROR